### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/minimal-new-tab#1]
- [x] Remove/Edit recent item entries
- [x] Arrow key navigation on suggestions
- [x] alternative placeholder logo so we can submit to the chrome store
- [x] Favicon population on first load
- [x] refresh favicons for shifted favorites

April 2021

- [x] replace undefined favicons with default
- [x] last element in suggestions styling
- [ ] support different search engines
- [x] general code cleanup
- [ ] shorter css names
- [ ] better setactive()

**Comment by downthecrop** [comment]
Todo:

- [ ] replace undefined favicons with default
- [ ] last element in suggestions styling
- [ ] support different search engines
- [ ] general code cleanup

**Comment by downthecrop** [comment]
https://coderwall.com/p/nygghw/don-t-use-innerhtml-to-empty-dom-elements

**Comment by downthecrop** [comment]
Topsite can bug this if there are too few entries. Could use a little length test.

**Comment by downthecrop** [comment]
https://gist.github.com/niksumeiko/360164708c3b326bd1c8#file-disable-html-form-input-autocomplete-autofill-md

**Comment by downthecrop** [comment]
> Topsite can bug this if there are too few entries. Could use a little length test.

a4faea9

**Comment by downthecrop** [comment]
Todo: rewrite in vue
